color: null
fieldLayouts:
  da0042e2-d291-4209-b6e1-765369882a4a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-26T17:01:07+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Name
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 73fa3f2f-15ba-452c-bf83-22f6c269d750
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-27T08:54:21+00:00'
            elementCondition: null
            fieldUid: ee6d383e-e5e6-4bf3-bf33-3ccd8d4adb8a # Text Field
            handle: docAddress
            includeInCards: false
            instructions: null
            label: Address
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8343e2f3-e7ee-416b-a195-c7d72b6dabbc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-27T09:02:05+00:00'
            elementCondition: null
            fieldUid: ee6d383e-e5e6-4bf3-bf33-3ccd8d4adb8a # Text Field
            handle: docProfession
            includeInCards: false
            instructions: null
            label: Profession
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5d4f5511-5dc9-4438-bef6-93173f0926d7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-27T15:04:22+00:00'
            elementCondition: null
            fieldUid: ee6d383e-e5e6-4bf3-bf33-3ccd8d4adb8a # Text Field
            handle: docPhone
            includeInCards: false
            instructions: null
            label: 'Phone Number'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f4c1d531-b9c0-4bf5-96ee-e93245fea19f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-27T08:54:21+00:00'
            elementCondition: null
            fieldUid: ee6d383e-e5e6-4bf3-bf33-3ccd8d4adb8a # Text Field
            handle: docStreet
            includeInCards: false
            instructions: null
            label: 'Street / Number'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f70924a0-2caa-4e9b-ab1f-a421ddcfd471
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-27T08:54:21+00:00'
            elementCondition: null
            fieldUid: 081924e9-6624-4e96-a202-5bd71ea7d7ce # ZIP Code
            handle: docZipCode
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 077804cf-3af0-455c-be60-95a86e009d7d
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-02-27T08:54:21+00:00'
            elementCondition: null
            fieldUid: ee6d383e-e5e6-4bf3-bf33-3ccd8d4adb8a # Text Field
            handle: docCity
            includeInCards: false
            instructions: null
            label: City
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 279e9891-8e85-4aeb-a4c0-aa66466882bd
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-02-27T09:58:58+00:00'
            elementCondition: null
            fieldUid: ee6d383e-e5e6-4bf3-bf33-3ccd8d4adb8a # Text Field
            handle: docCanton
            includeInCards: false
            instructions: null
            label: Canton
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cbf09813-74fe-4152-8c43-5cdd9040a1c7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-27T14:33:21+00:00'
            elementCondition: null
            fieldUid: 12074a27-13af-4f17-bb99-f7c6c45f0e7f # Link / URL
            handle: googleUrl
            includeInCards: false
            instructions: null
            label: 'Google Search URL'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a406ba75-c03c-4513-a9c4-170b2b0aba8c
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-02-27T08:54:21+00:00'
            elementCondition: null
            fieldUid: 12074a27-13af-4f17-bb99-f7c6c45f0e7f # Link / URL
            handle: onedocUrl
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 18217b29-1577-44d3-b165-cab9415294f3
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-02-27T10:56:39+00:00'
            elementCondition: null
            fieldUid: 889df0e9-d8a5-41ac-a9c5-bea7d7572523 # CRM Status
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 99c6b4b2-1e12-4bef-bea5-01be8b56df65
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: d7fc051b-a001-4409-ad2b-479fcc4eb7a7
        userCondition: null
handle: crmEntry
hasTitleField: true
icon: address-book
name: 'CRM Entry'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
