columnSuffix: null
handle: profession
instructions: null
name: Profession
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - ''
        -
          - value
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
