columnSuffix: null
handle: zuweisung
instructions: null
name: Zuweisung
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
