dateModified: 1740668662
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: '*'
      tableAttributes:
        - status
        - section
        - postDate
        - expiryDate
        - link
      type: native
    -
      heading: 'CRM Entries'
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:d1f88d76-38c8-4a14-ad7a-6857783a066d' # Doctors
      tableAttributes:
        - 'fieldInstance:5d4f5511-5dc9-4438-bef6-93173f0926d7'
        - 'fieldInstance:f70924a0-2caa-4e9b-ab1f-a421ddcfd471'
        - 'fieldInstance:077804cf-3af0-455c-be60-95a86e009d7d'
        - 'fieldInstance:279e9891-8e85-4aeb-a4c0-aa66466882bd'
        - 'field:889df0e9-d8a5-41ac-a9c5-bea7d7572523' # CRM Status
      type: native
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:2c3c9efa-9e65-4c75-8835-9398b8f7b353' # Clinics
      tableAttributes:
        - 'fieldInstance:f70924a0-2caa-4e9b-ab1f-a421ddcfd471'
        - 'fieldInstance:077804cf-3af0-455c-be60-95a86e009d7d'
        - 'fieldInstance:279e9891-8e85-4aeb-a4c0-aa66466882bd'
        - 'fieldInstance:cbf09813-74fe-4152-8c43-5cdd9040a1c7'
        - 'field:889df0e9-d8a5-41ac-a9c5-bea7d7572523' # CRM Status
      type: native
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:da503bc9-5d31-492d-900c-e2bb7a64bdc6' # Medical Centers
      tableAttributes:
        - 'fieldInstance:f70924a0-2caa-4e9b-ab1f-a421ddcfd471'
        - 'fieldInstance:077804cf-3af0-455c-be60-95a86e009d7d'
        - 'fieldInstance:279e9891-8e85-4aeb-a4c0-aa66466882bd'
        - 'fieldInstance:cbf09813-74fe-4152-8c43-5cdd9040a1c7'
        - 'field:889df0e9-d8a5-41ac-a9c5-bea7d7572523' # CRM Status
      type: native
    -
      heading: ''
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:60a1ba8b-645d-493d-ac68-5460fb68629f' # Group Practices / Gruppenpraxis
      tableAttributes:
        - 'fieldInstance:f70924a0-2caa-4e9b-ab1f-a421ddcfd471'
        - 'fieldInstance:077804cf-3af0-455c-be60-95a86e009d7d'
        - 'fieldInstance:279e9891-8e85-4aeb-a4c0-aa66466882bd'
        - 'fieldInstance:cbf09813-74fe-4152-8c43-5cdd9040a1c7'
        - 'field:889df0e9-d8a5-41ac-a9c5-bea7d7572523' # CRM Status
      type: native
email:
  fromEmail: hello@pom-pom.ch
  fromName: CRM
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    1fc7f24d-e20d-4a38-88f1-ca973df46059: CRM # CRM
    2c3c9efa-9e65-4c75-8835-9398b8f7b353: Clinics # Clinics
    59bd424f-4b4e-4449-898f-c3c927f0a4c8: CRM # CRM
    60a1ba8b-645d-493d-ac68-5460fb68629f: 'Group Practices / Gruppenpraxis' # Group Practices / Gruppenpraxis
    889df0e9-d8a5-41ac-a9c5-bea7d7572523: 'CRM Status' # CRM Status
    12074a27-13af-4f17-bb99-f7c6c45f0e7f: 'Link / URL' # Link / URL
    081924e9-6624-4e96-a202-5bd71ea7d7ce: 'ZIP Code' # ZIP Code
    05122057-522b-4eca-93d3-827592ca5f53: Profession # Profession
    d1f88d76-38c8-4a14-ad7a-6857783a066d: Doctors # Doctors
    da503bc9-5d31-492d-900c-e2bb7a64bdc6: 'Medical Centers' # Medical Centers
    dc6cf8eb-22af-4b1d-8b65-efefa371adf9: 'CRM Entry' # CRM Entry
    ee6d383e-e5e6-4bf3-bf33-3ccd8d4adb8a: 'Text Field' # Text Field
plugins:
  feed-me:
    edition: standard
    enabled: true
    schemaVersion: 5.1.1
system:
  edition: solo
  live: true
  name: CRM
  retryDuration: null
  schemaVersion: 5.6.0.2
  timeZone: Europe/Zurich
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
