dateModified: 1767888814
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: '*'
      tableAttributes:
        - status
        - section
        - postDate
        - expiryDate
        - link
      type: native
    -
      heading: 'CRM Entries'
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:d1f88d76-38c8-4a14-ad7a-6857783a066d' # Doctors
      tableAttributes:
        - 'fieldInstance:5d4f5511-5dc9-4438-bef6-93173f0926d7'
        - 'fieldInstance:f70924a0-2caa-4e9b-ab1f-a421ddcfd471'
        - 'fieldInstance:077804cf-3af0-455c-be60-95a86e009d7d'
        - 'fieldInstance:279e9891-8e85-4aeb-a4c0-aa66466882bd'
        - 'field:889df0e9-d8a5-41ac-a9c5-bea7d7572523' # CRM Status
      type: native
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:2c3c9efa-9e65-4c75-8835-9398b8f7b353' # Clinics
      tableAttributes:
        - 'fieldInstance:cbf09813-74fe-4152-8c43-5cdd9040a1c7'
        - 'fieldInstance:8343e2f3-e7ee-416b-a195-c7d72b6dabbc'
        - 'fieldInstance:f4c1d531-b9c0-4bf5-96ee-e93245fea19f'
        - 'fieldInstance:5d4f5511-5dc9-4438-bef6-93173f0926d7'
        - 'field:12074a27-13af-4f17-bb99-f7c6c45f0e7f' # Link / URL
        - 'fieldInstance:a406ba75-c03c-4513-a9c4-170b2b0aba8c'
        - 'fieldInstance:88073a01-8f63-47b3-836f-c2fa7c41696e'
        - 'field:c2fc5bbf-79d0-4c09-a4e8-c71748f11879' # Zuweisung
        - 'field:889df0e9-d8a5-41ac-a9c5-bea7d7572523' # CRM Status
      type: native
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:da503bc9-5d31-492d-900c-e2bb7a64bdc6' # Medical Centers
      tableAttributes:
        - 'fieldInstance:cbf09813-74fe-4152-8c43-5cdd9040a1c7'
        - 'fieldInstance:8343e2f3-e7ee-416b-a195-c7d72b6dabbc'
        - 'fieldInstance:f4c1d531-b9c0-4bf5-96ee-e93245fea19f'
        - 'fieldInstance:5d4f5511-5dc9-4438-bef6-93173f0926d7'
        - 'field:12074a27-13af-4f17-bb99-f7c6c45f0e7f' # Link / URL
        - 'fieldInstance:a406ba75-c03c-4513-a9c4-170b2b0aba8c'
        - 'field:c2fc5bbf-79d0-4c09-a4e8-c71748f11879' # Zuweisung
        - 'fieldInstance:88073a01-8f63-47b3-836f-c2fa7c41696e'
        - 'field:889df0e9-d8a5-41ac-a9c5-bea7d7572523' # CRM Status
      type: native
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:60a1ba8b-645d-493d-ac68-5460fb68629f' # Group Practices / Gruppenpraxis
      tableAttributes:
        - 'fieldInstance:cbf09813-74fe-4152-8c43-5cdd9040a1c7'
        - 'fieldInstance:8343e2f3-e7ee-416b-a195-c7d72b6dabbc'
        - 'fieldInstance:5d4f5511-5dc9-4438-bef6-93173f0926d7'
        - 'field:12074a27-13af-4f17-bb99-f7c6c45f0e7f' # Link / URL
        - 'fieldInstance:a406ba75-c03c-4513-a9c4-170b2b0aba8c'
        - 'fieldInstance:88073a01-8f63-47b3-836f-c2fa7c41696e'
        - 'field:c2fc5bbf-79d0-4c09-a4e8-c71748f11879' # Zuweisung
        - 'field:889df0e9-d8a5-41ac-a9c5-bea7d7572523' # CRM Status
      type: native
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:0a308f24-46a3-4232-b91f-585f5d8520a8' # Medizinische Praxis
      tableAttributes:
        - 'fieldInstance:cbf09813-74fe-4152-8c43-5cdd9040a1c7'
        - 'fieldInstance:8343e2f3-e7ee-416b-a195-c7d72b6dabbc'
        - 'fieldInstance:f4c1d531-b9c0-4bf5-96ee-e93245fea19f'
        - 'fieldInstance:5d4f5511-5dc9-4438-bef6-93173f0926d7'
        - 'field:12074a27-13af-4f17-bb99-f7c6c45f0e7f' # Link / URL
        - 'fieldInstance:a406ba75-c03c-4513-a9c4-170b2b0aba8c'
        - 'field:c2fc5bbf-79d0-4c09-a4e8-c71748f11879' # Zuweisung
        - 'fieldInstance:88073a01-8f63-47b3-836f-c2fa7c41696e'
        - 'field:889df0e9-d8a5-41ac-a9c5-bea7d7572523' # CRM Status
      type: native
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:90682f35-c686-4ef5-95b6-2979a8d511a1' # Hospitals
      tableAttributes:
        - 'fieldInstance:cbf09813-74fe-4152-8c43-5cdd9040a1c7'
        - 'fieldInstance:8343e2f3-e7ee-416b-a195-c7d72b6dabbc'
        - 'fieldInstance:f4c1d531-b9c0-4bf5-96ee-e93245fea19f'
        - 'fieldInstance:5d4f5511-5dc9-4438-bef6-93173f0926d7'
        - 'field:12074a27-13af-4f17-bb99-f7c6c45f0e7f' # Link / URL
        - 'fieldInstance:a406ba75-c03c-4513-a9c4-170b2b0aba8c'
        - 'field:c2fc5bbf-79d0-4c09-a4e8-c71748f11879' # Zuweisung
        - 'fieldInstance:88073a01-8f63-47b3-836f-c2fa7c41696e'
        - 'field:889df0e9-d8a5-41ac-a9c5-bea7d7572523' # CRM Status
      type: native
email:
  fromEmail: hello@pom-pom.ch
  fromName: CRM
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    0a308f24-46a3-4232-b91f-585f5d8520a8: 'Medizinische Praxis' # Medizinische Praxis
    1fc7f24d-e20d-4a38-88f1-ca973df46059: CRM # CRM
    2c3c9efa-9e65-4c75-8835-9398b8f7b353: Clinics # Clinics
    59bd424f-4b4e-4449-898f-c3c927f0a4c8: CRM # CRM
    60a1ba8b-645d-493d-ac68-5460fb68629f: 'Group Practices / Gruppenpraxis' # Group Practices / Gruppenpraxis
    889df0e9-d8a5-41ac-a9c5-bea7d7572523: 'CRM Status' # CRM Status
    12074a27-13af-4f17-bb99-f7c6c45f0e7f: 'Link / URL' # Link / URL
    081924e9-6624-4e96-a202-5bd71ea7d7ce: 'ZIP Code' # ZIP Code
    90682f35-c686-4ef5-95b6-2979a8d511a1: Hospitals # Hospitals
    05122057-522b-4eca-93d3-827592ca5f53: Profession # Profession
    73644798-b9e8-44d8-81ca-748ece161994: 'Public Schema' # Public Schema
    c2fc5bbf-79d0-4c09-a4e8-c71748f11879: Zuweisung # Zuweisung
    d1f88d76-38c8-4a14-ad7a-6857783a066d: Doctors # Doctors
    da503bc9-5d31-492d-900c-e2bb7a64bdc6: 'Medical Centers' # Medical Centers
    dc6cf8eb-22af-4b1d-8b65-efefa371adf9: 'CRM Entry' # CRM Entry
    ee6d383e-e5e6-4bf3-bf33-3ccd8d4adb8a: 'Text Field' # Text Field
plugins:
  _meditransfer-mailer:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  dashboard-begone:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  feed-me:
    edition: standard
    enabled: true
    schemaVersion: 5.14.0
system:
  edition: solo
  live: true
  name: CRM
  retryDuration: null
  schemaVersion: 5.8.0.3
  timeZone: Europe/Zurich
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
